
export CODEJAM_GITHUB_CLIENT_ID=""
export CODEJAM_GITHUB_CLIENT_SECRET=""
export CODEJAM_GITHUB_POSTGRES_DATABASE=""
export CODEJAM_GITHUB_POSTGRES_PASSWORD=""
export CODEJAM_GITHUB_POSTGRES_PORT=""
export CODEJAM_SESSION_SALT=""
export CODEJAM_SECRET_KEY_BASE=""
export CODEJAM_GITHUB_ACCESS_TOKEN=""